### ISSUE TITLE
Delete vocabulary card

### ISSUE THREAD

**Issue by carinamenke** [carinamenke/vorto#24]
## Value statement - a requirement, not a solution
As a **user** 
I need **to delete vocabulary cards** 
so that **I can get rid of cards which are not relevant for me.** 

## Description (Text, Scribble, Wireframe, Design)
- Add a delete symbol in the card detail view which will delete the respective card on click:
<img width="372" alt="Bildschirmfoto 2020-03-30 um 17 07 01" src="https://user-images.githubusercontent.com/17109650/77928673-01980180-72a9-11ea-802c-26e497b9cbf9.png">

## Acceptance criteria
- [x] Cards can be deleted by clicking on delete button inside the detail view of a card
- [x] After click on the delete button, a modal appears, asking users to confirm the deletion. Users can either confirm or cancel inside the modal: 
- [x]  -> After click on cancel button: modal closes and card remains in the same position as before.
- [x] -> After click on confirm button: modal closes and card has disappeared and is deleted from local storage.

## Tasks
- [ ] Write unit tests
- [x] Add delete button in card detail view
- [x] Implement delete logic including deletion of image and audio files from firebase storage
- [x] Add a modal for deletion confirmation
- [x] Update edited components in  Storybook
- [x] Adapt and extend Cypress tests
- [x] Test on mobile and desktop, in FF, Chrome and Safari

## Size
Small
