### ISSUE TITLE
Image & audio preview/upload

### ISSUE THREAD

**Issue by carinamenke** [carinamenke/vorto#38]
## Value statement - a requirement, not a solution
As a **user** 
I need **to upload image and audio files** 
so that **I can add them to my vocabulary cards and make the learning experience a little more interactive and enjoyable.** 

## Description (Text, Scribble, Wireframe, Design)
* Expand the existing image and audio upload components so that users see a preview of their selected files in the form and that the data is shown in the vocabulary cards after the form is submitted.
<img width="333" alt="Bildschirmfoto 2020-03-26 um 15 26 10" src="https://user-images.githubusercontent.com/17109650/77657863-2b35ed80-6f76-11ea-8e15-4e9606a14b39.png">

## Acceptance criteria
- [x] Images and audio files can be slected and uploaded via the respective components in the form
- [x] The selected image is displayed as a preview within the form
- [x] For selected audio files, the file name is displayed as a preview in the form
- [x] Both image a audio files are saved to Firebase storage
- [x] After form submit, the image and audio files are added to the newly created card. The file urls are saved with the other card data to the local storage

## Tasks
- [ ] Write tests
- [x] Set up firebase cloud storage
- [x] Expand the existing form, image and audio upload components with logic to send and receive image and audio data from firebase storage
- [x] Update edited components in  Storybook
- [ ] Adapt and extend Cypress tests
- [x] Test on mobile and desktop, in FF, Chrome and Safari

## Size
Medium
