### ISSUE TITLE
Vocabulary search

### ISSUE THREAD

**Issue by carinamenke** [carinamenke/vorto#7]
## Value statement - a requirement, not a solution
As a **user** 
I want **to use a search field** 
so that **I can find specific vocabs easily** 

## Description (Text, Scribble, Wireframe, Design)
- A separate page with a search field 
- Search results are loaded on the page below the search field
<img width="313" alt="Bildschirmfoto 2020-03-15 um 20 34 52" src="https://user-images.githubusercontent.com/17109650/76709248-a1785b80-66fd-11ea-950e-028a0de89373.png">

## Acceptance criteria
- [x] Search page can be accessed via navigation
- [x] A search field can be filled with seach terms
- [x] The search can be triggered via the enter key or the search button next to the search field
- [x] A counter inidcates the number of found serch results
- [x] As soon as the input field is entered, a delete icon appears in the search field
- [x] A click on the delete icon clears the search field
- [x] Vocabulary cards with words that match the search are shown below the search field as soon as the search is triggered
- [x] Only exact matches are shown (no fuzzy search for now?)

## Tasks
- [ ] Write tests
- [x] Ceate a component for the search input
- [x] Add new component to Storybook
- [x] Set up a new Cypress test
- [x] Test on mobile and desktop, in FF, Chrome and Safari

## Size
Medium
