### ISSUE TITLE
Navigation and header

### ISSUE THREAD

**Issue by carinamenke** [carinamenke/vorto#9]
## Value statement - a requirement, not a solution
As a **user** 
I need **to access the different pages in the app** 
so that **I can navigate between the card list, card form and search page** 

## Description (Text, Scribble, Wireframe, Design)
* A sticky navigation at the bottom of the each page
* It has three navigation points: Home, new Card form and Search Page
<img width="408" alt="Bildschirmfoto 2020-03-12 um 21 27 05" src="https://user-images.githubusercontent.com/17109650/76563728-4699f680-64a8-11ea-952e-330122e88754.png">
* The logo is show in the header on certain pages
<img width="403" alt="Bildschirmfoto 2020-03-14 um 18 05 04" src="https://user-images.githubusercontent.com/17109650/76686803-7c60eb80-661e-11ea-8214-16f80707d662.png">

## Acceptance criteria
- [x] Header is shown on the home and search page
- [x] Header is sticky
- [x] Header is styled as shown in design
- [x] Navigation is sticky at bottom of the page
- [x] Navigation shows on all pages except for card detail overlay
- [x] Navigation is styled as in design
- [x] Active navigation points are highlighted in primary colour
- [x] URL changes when moving to another page

## Tasks
- [x] Add routes for different pages 
- [ ] Write tests
- [x] Adapt Cypress test
- [x] Set up empty search page
- [x] Add components to Storybook
- [x] Test on mobile and desktop, in FF, Chrome and Safari

## Size
(small, medium, large)
